#!/bin/bash
#
CURRENT=$(pwd)
cd $(dirname $0)
DOTFILE_DIR=$(pwd)
cd ${CURRENT}

if [ ! -f "$(dirname $0)/.bootstrapped" ]; then
	git submodule init
	git submodule update
	touch $(dirname $0)/.bootstrapped
fi

HOOK="source ${DOTFILE_DIR}/.bashrc"
if [ "" == "$(cat ~/.bashrc | grep "^${HOOK}")" ]; then
	echo ${HOOK} >> ~/.bashrc
	${DOTFILE_DIR}/scripts/mount envs/nodenv envs/vim
	DEFAULT_NODEJS_VERSION="4.4.7"
	PATH=${PATH}:$HOME/.nodenv/bin nodenv install -s ${DEFAULT_NODEJS_VERSION}
	PATH=${PATH}:$HOME/.nodenv/bin nodenv global ${DEFAULT_NODEJS_VERSION} && echo "successfully use nodejs ${DEFAULT_NODEJS_VERSION} as default"
	# PATH=${PATH}:$HOME/.nodenv/bin nodenv install -s 4.8.1
	# PATH=${PATH}:$HOME/.nodenv/bin nodenv install -s 6.10.1
	# PATH=${PATH}:$HOME/.nodenv/bin nodenv install -s 7.8.0
	
	NODE_MODULE_DIR="$(dirname $($HOME/.nodenv/bin/nodenv which npm))/node_modules"
	UIDN="${NODE_MODULE_DIR}/npm/node_modules/uid-number/uid-number.js"
	if [ "true" == "${FORCE_ROOT_USER_IN_QEMU}" ]; then
		echo "backup ${UIDN}"
		mv ${UIDN} ${UIDN}.bak
		echo "module.exports = function uidNumber(uid, gid, cb) {cb(null, 0, 0)}" > ${UIDN}
	fi
	
	$($HOME/.nodenv/bin/nodenv which npm) --version
	$($HOME/.nodenv/bin/nodenv which npm) install -g livescript@1.5.0
	PATH=${PATH}:$HOME/.nodenv/bin nodenv rehash
	
	if [ "true" == "${FORCE_ROOT_USER_IN_QEMU}" ]; then
		echo "restore ${UIDN}"
		rm -f ${UIDN}
		mv ${UIDN}.bak ${UIDN}
	fi	
else
	echo "already mounted"
fi
