#!/bin/bash

if [ "" == "${HOME}" ]; then
	[ "root" == "$(whoami)" ] && export HOME="/root" || export HOME="/home/$(whoami)"
fi

if [ ! -f "/tmp/nodenv" ]; then
	cd ${HOME}/.nodenv && src/configure && make -C src
	touch /tmp/nodenv
fi

export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"
